---
title: 'Project 2: Correlation'
author: "Eric Anku"
date: "3/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r import-libraries}
# Import libraries for data analysis

pacman::p_load(
        tidyverse, #Data management and plots
        rio, # Data import
        here, #Project management
        janitor, #Clean data names
        skimr, #Skim dataset
        gtsummary, #Table summary
        finalfit # Labeling of variables
)
```

```{r load-dataset}
df <- import(here("data","birthweight_dataset.sav")) #Import dataset
```


```{r clean-data}
df <- clean_names(df) #clean data variables
```


```{r data-transformation}
df <- df%>%mutate(
        smoker = factor(smoker)%>%
                fct_recode("No smoker" = "0",
                           "Smoker" = "1")%>%
                ff_label("Smoker"),
        lowbwt = factor(lowbwt)%>%
                fct_recode("No" = "0",
                           "Yes" = "1")%>%
                ff_label("Low birth weight"),
        mage35 = factor(mage35)%>%
                fct_recode("No" = "0",
                           "Yes" = "1")%>%
                ff_label("Maternal age group")
)
```

```{r skim-data}
df_no_id <- df%>%select(-c(id))
skim(df_no_id)
```



```{r subset-data-smoking-mothers}
df_smoker <- df%>%
        filter (smoker == "Smoker") ## Data frame for smoking mothers
```



```{r subset-data-non-smoking-mothers}
df_non_smoker <- df%>%
        filter(smoker == "No smoker")
```

There are `r nrow(df)` children in this study. 

```{r}
df%>%
        tbl_summary()
```
 












